version: 2

project_name: spanforge

before:
  hooks:
    - go test ./...

builds:
  - id: spanforge
    binary: spanforge
    main: ./cmd/spanforge
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

dockers_v2:
  - id: spanforge
    dockerfile: Dockerfile.goreleaser
    ids:
      - spanforge
    images:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/spanforge
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64

release:
  draft: false
